### ISSUE TITLE
service: Build data model and read-only API

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#128]
Precondition: organization and location data models are in place.

Acceptance Criteria:

* When importing data from BC211 XML input, all fields are included as per the tables below, the service_at_location table being populated to indicate which location each service is available at. 
* A GET request to /services/ returns a list of all services with all the fields populated
* A GET request to /services/{id} returns the services with the given id
* A GET request to /organizations/{id}/services/ returns a list of all services under the given organization
* A GET request to /organizations/{id}/services/{id} returns the services with the given organization and service ids

One small unknown: Given the BC211 XML format with the service being child nodes of locations, either each service is available at one location only, or else the services are duplicated under each location where they are available. This should not be too hard to figure out once we have a parser.

service: 

Name | BC211 XPath | Translatable
-- | -- | --
id   | Source/Agency/Site/SiteService/Key | No
organization_id   |  Source/Agency/Key | No
name |   Source/Agency/Site/SiteService/Name | Yes
description |   Source/Agency/Site/SiteService/Description  | Yes

service_at_location:

| Name |
|----|
| service_id |
| location_id |

**Comment by dylanmccall** [comment]
With regards to that unknown part: in [the HSDA spec](http://openreferral.readthedocs.io/en/latest/hsda/hsda/#get--services-), there is only a single location id for a given service record. So, for our purposes, it's a one-to-many relationship where you have one location per service. (And the only reason we manage that relation in another table is for the pesky "description" field).

That it's a one-to-one instead of one-to-many relation does strike me as rather bizarre, so we may want to bring that up upstream and make sure it's all for a good reason.

**Comment by rasmus-storjohann-PG** [comment]
Yeah, it's a many to many. That's probably why you put the location property on the service DTO, but it makes sense to remove that too.
