### ISSUE TITLE
Plan translation tracking mechanism of translatable content

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-backend#149]
AC: Produce one or more stories defining the work needed for us to be able to determine, at any given time, what translation work is required to complete the set of translations in the system. In order to do this, we need to be able to determine which translations are missing and which translations are stale. For future-proofing, we also need to have an idea of how we would support having more than one source language, but for the BC deployment we can assume that the source language is English.

The implementation work will be tracked in #133 which will be updated with detailed ACs as part of the work under this planning story.

Ideas:
* There are two kinds of string values in the system, source strings and translated strings. Source strings are in the source language and are updated when the owner of that record changes information in the record. We currently assume that the source language is English.
* Translated strings are in some other language and are updated when new translations are imported.  Translated strings cannot be changed by any other mechanism.
* When a source string is added or changed, a version id associated with the string is updated. The version id may take the form of an integer counter or a time stamp. When source strings are exported for translation, their version ids are exported along with it.
* The version is associated with the record containing the translated string. Alternatives is to have a version associated with each string, or to associate it with an owning record.
* When a translation is imported into the system, the version id of the string in the translated data is compared to the version id of the corresponding source string. If they are different, it is an error: The source string was changed while the translation was in progress. This means that the translated string invalid, so it will not be imported.
* If the version identifiers match, the string is imported and saved. The version id for the translated field is updated to reflect the version id in the imported translated data. 
* The mechanism used to store different strings for each supported language is also used to store the version identifiers for the record, so that for a given record and a given language, we can retrieve the version identifier. Assuming the source is English, or in the future, retrieving the source language id from the record, we can retrieve the version identifier of the source language, and compare to determine whether the translation in each language is stale, or whether it is valid to import a given new translated string with its version id.

**Comment by rasmus-storjohann-PG** [comment]
@dylanmccall can you please review this story and tell me if this all makes sense to you?

**Comment by dylanmccall** [comment]
I've thought about it a little and I'm still not following why we want to root revision IDs so deeply into our translation workflow that we're exposing them externally. Usually translation systems based on gettext will just treat the string itself as a unique identifier. If it changes, the translation needs to be updated; if it does not, it's fine. Then translation tools like Transifex can use some smarts to keep translations for old source strings attached to new source strings, usually based on the string context (which we provide). Are there some particular issues with that which I'm not seeing?

One thing I think will be a good task here is defining our own TranslatableModel base class that could hold the functionality we need for keeping track of source languages. We would definitely benefit from a way to understand *internally* when a source string has been modified so that we know when translation templates for each content type need to be exported.

**Comment by rasmus-storjohann-PG** [comment]
Given @dylanmccall 's comment and my incomplete understanding of how translation will actually work, I think the best way is to put off further planning and development in this area until we have done one round of translation (either thin thread style or a more complete sweep) and develop an approach to handling translation of changing content then. Leaving this story open and in the backlog for now to keep track of the thoughts on the issue.
