### ISSUE TITLE
Add a mechanism for test-specific models and data

### ISSUE THREAD

**Issue by dylanmccall** [pg-irc/pathways-backend#150]
This project is broken up into many small, loosely coupled applications. Testing one of those applications may require that we write tests which use a model that is only for testing. We should figure out how we're going to do that.

One approach is explained over here, with a custom test runner that loads a separate settings file for tests:

https://docs.djangoproject.com/en/1.11/topics/testing/advanced/#using-the-django-test-runner-to-test-reusable-applications

**Comment by rasmus-storjohann-PG** [comment]
I'm not convinced that tracking this kind of problem is a good use of an issue, because it will always remain low priority and never actually resolved. As you run into this kind of problem, make a solution in code, before during or after which get in touch with me if you like so we can discuss possible solutions. Clean Code is again a very good source for how to do this.
