### ISSUE TITLE
Clean BC211 June 2019 Data

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-backend#391]
The new data set has various changes which affect how the services look on our app: 

![Screenshot_20190705-144923_Arrival Advisor.jpg](https://images.zenhubusercontent.com/5c6c8cff9d62b128eab447ff/018763a9-b593-465d-a5d7-3ea47c2d3a83)![Screenshot_20190705-144929_Arrival Advisor.jpg](https://images.zenhubusercontent.com/5c6c8cff9d62b128eab447ff/3f16e7c2-8d8a-49af-8bca-64b6b249c167)

### Acceptance Criteria: 

- [ ] Find out how the service description titles are being generated on the client 
`Why is Child_and_youth_services showing up on service list description with a phone number?`
- [ ] Replace fields with more readable names 
`e.g TTY: 604-604-1111 should be Phone: 604-604-1111`

**Comment by ArtiBPG** [comment]
@tomy-pg can you estimate how big this problem is?

**Comment by ian-lin-PG** [comment]
A service site can have multiple phone numbers each having a different type. This I believe was used to support multiple numbers such as phone and fax for a given service. Some services went further by providing a number for each service they provide in this form:
![image](https://user-images.githubusercontent.com/52009863/61658127-82fab700-ac79-11e9-9fe1-28b02f8300f7.png)

Tty is also valid because it is a type of phone number in the same format:
![image](https://user-images.githubusercontent.com/52009863/61658225-c2290800-ac79-11e9-873b-10f661baf230.png)

I don't think this is a new phenomena, I saw similar instances in the production app. I am not sure what's the next steps.

**Comment by ArtiBPG** [comment]
@ian-lin-PG can we use the text in the <Type> tag so that instead of:
**Child_and_youth_services** 
we see:
**Child and youth services:**

**Comment by cherrielam** [comment]
Agree with Arti. 
Also while we're at it, is it possible to remove Fax? 
Multiple people have been surprised at the Fax result and noted that it's not useful in a Mobile app setting.

**Comment by ArtiBPG** [comment]
@cherrielam lets not remove fax info- there may be a situation where service canada requires you to send them a fax.

**Comment by ian-lin-PG** [comment]
I can do something about the underlines, I will check with Rasmus about why it was added in the first place tomorrow.

**Comment by ian-lin-PG** [comment]
The underline is removed, the change is in #412 or pg-irc/pathways-frontend#537. The reason is because that issues is the larger phone number parsing change.

**Comment by rasmus-storjohann-PG** [comment]
QA: Loaded data into the DB and looked for phone number types containing '_'. There were no such phone number types. Reviewed the phone number types, they all are pretty human readable I would say. Passed.
