### ISSUE TITLE
As an Anonymous user, I can view 211 services on a map in the user interface.

### ISSUE THREAD

**Issue by tuckerbuchy** [pg-irc/pathways-backend#73]

**Comment by dylanmccall** [comment]
Removing the bottom two bullet points as they are out of scope for this ticket and quite a bit more complex to implement. However, I'm uncertain if we should leave this user story open, seeing as the code we have is plainly a proof of concept and needs some real development work to function at all well.

**Comment by tuckerbuchy** [comment]
@dylanmccall nice work. Yeah, we should definitely capture these additional requirements somewhere. Perhaps we can tie this one up, and then open a few tickets under this epic more specifically about these extra features (filtering and map viewport stuff).

I suppose we want to add logic to return only locations within an area that is proportional to the viewport the user is looking at too?

**Comment by tuckerbuchy** [comment]
Is this operational? Can I try it out on my local?

**Comment by dylanmccall** [comment]
You sure can! Although I need to update the readme. Will do in a few minutes...

Incidentally, I'm using [Yarn](yarnpkg.com/en/docs/getting-started) instead of NPM here, so there's a yarn.lock file instead of package-lock.json. You may want to use `yarn install` if you happen to have yarn available, but no big deal if not.

**Comment by tuckerbuchy** [comment]
Awesome thanks. Trying to put this up on Heroku currently.
