### ISSUE TITLE
Create wireframes for Pathways administrative creation and management.

### ISSUE THREAD

**Issue by tuckerbuchy** [pg-irc/pathways-backend#95]
We want to create some wireframes for the views that Admins will use to create Pathways for users to follow.

Find relevant terminology defined here:
#37 

Some requirements:

* Users can create custom Stages
  * Stages support having an order of completion/dependency.
* Users can create custom Actions
  * Actions can be associated with Stages
  * Actions support having an order of completion/dependency.
* During action creation, the admin can define the query that will be performed to retrieve the relevant services.
  * This process can allow experimentation through a **Test** button.
  * The admin can optionally associate Keywords to search on.
* Admins can set "Discovery" criteria based on what user profiles the Actions will show up for.
  * e.g. Age groupings, Settlement status.

**Comment by tuckerbuchy** [comment]
Worked on a wireframe for this today:
![wireframe 1](https://user-images.githubusercontent.com/2782487/29685514-98952c78-88ca-11e7-957c-38143c72f1fa.png)
source: https://drive.google.com/open?id=0B6riHKIYojeGczJJMFZ1d1JxRkk
@dylanmccall @mackh @PeaceGeeks @pierrebeugnot @davidascher @robinpuga 
Comments appreciated and welcome!

**Comment by amyngai** [comment]
Hey @tuckerbuchy , good first pass! I have a few comments and questions. Happy to talk over some higher level q's over slack. That said, I'll brain dump below:

---

Higher level questions:
- I'm assuming this is for an administrator who is creating custom pathways
   - my question is whether it's for a specific person? or more of a 1 time set up 
   - if the former, we should optimize for ease of use (small things like drag and drop vs a button to move an item up and down or have a better visual layout). if the latter, we can worry about that later as it won't be as important since they won't be changed often.

Vocabulary
- I know these names were established prior, but as someone new to this interface, I personally had some confusion about the names. 
   - actions - great, very descriptive
   - stage - doesn't totally make sense conceptually (i think we can talk to the immigrant committee to come up with something that would make a bit more sense initially). Perhaps `Need` or `Support Path` I'll keep thinking here
- "Discovery"
    - discovery --> `details`? `settings`? 
	- i assume this name was chosen because the action will be "discovered" by an end user
	- the name doesn't need to be this specific in an admin panel
        - the icon is also a little confusing. The eye icon is typically used to show/hide items 

- "Test"
   - test  --> `preview` ?
   - "Preview" is a more obvious word if you're previewing the outcome of clicking that stage

Wireframes:
- When creating a Stage name
    - It would ideal if previously made stages appeared first to help the admin create new stages based on previous ones. No need to create something new each time. 
   - Is ^ this possible? this is also affected by my earlier question of if this is a thing that's made often, (more custom per user vs made from scratch)

- where do the actions come from?
	- from the wires, they look autofilled?
	- autofill would be ideal. That way, the admin can get a list and customize it by deleting actions rather than adding. The former should be easier as they can see all actions available

- if an action is incomplete (doesn't have the "discovery") filled. there should be a warning to let them know if needs to be incomplete
   - would also be helpful to have an `all` checkbox. That way we can ensure that each action is complete 

---

hope this makes sense! pls ping me if you need more support!

**Comment by tuckerbuchy** [comment]
Wooo Awesome feedback thanks @amyngai.

Answers:
**I'm assuming this is for an administrator who is creating custom pathways
my question is whether it's for a specific person? or more of a 1 time set up**
It is not a one time set up, but something that will be continually added to, edited, etc. Basically, if new actions seem to be designed, an administrator can add them here.

**Comment by tuckerbuchy** [comment]
Updates done:
![pathways creation admin wireframes 1](https://user-images.githubusercontent.com/2782487/29785927-244924a2-8bde-11e7-9e14-2622a28d3ca1.png)

**Comment by davidascher** [comment]
Quick drive-by:

* agree with using drag and drop over loads of up/down arrows.  Probably want to consider clicking on the stages and actions make them 'selected', and show the edit/delete buttons only on selected (or, alternatively, on hover)
* one dangerous pattern is the list of checkboxes -- if there are lots of items in that list, it can easily get frustrating because you only see part of the list, it's irritating to have to navigate with a scrollbar, etc.  fine if there's only a few and they fit in the control.
* another anti-pattern is the highly modal nature of the penultimate screenshot for example with two dialogs that hide useful information.  Think about ways to show the preview in a separate part of the UI which doesn't overlay what the user was looking at.  Bonus points for doing a preview in a mobile phone-like UI, so people realize what users will actually look at most of the time.  Extra bonus points for letting people navigate the UI from the phone preview and showing the corresponding admin bits.
* Also, we should explore a horizontal layout (e.g. tabs) for the topmost level of hierarchy (housing, employment, education), rather than accordions. 
* the gear icon shows what you call 'settings' but they're not selected which makes me confused as to whether that's an editable control or not.  And if yes, why it would be different than the control used in the edit view.  If not, I don't know why they're the only things worth having a read-only view (as opposed to keywords for example).
